### ISSUE TITLE
[BUG] Russian and English keyboards act differently (win 10)

### ISSUE THREAD

**Issue by Viperwow** [greena13/react-hotkeys#184] opened 2019-05-23 13:44 UTC
**Describe the bug**
While writing hotkeys handling map I found out, that my sequence "ctrl + c" is not working while my system is not using English keyboard layout, but the Russian one. (the equivalent is "ctrl + с"). Keycodes exactly the same for both 'с' (en) and 'с' (ru) (according to http://keycode.info).
Seems ascii codes are the only difference.

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys, etc)**
HotKeys

**Expected behavior**
Key values do not depend on system locale input/ascii codes? (ru/en/whatever)

**Platform (please complete the following information):**
 - Version of react-hotkeys: 2.0.0-pre4/5
 - Browser: chrome, vivaldi
 - OS: Win 10 home (it seems MacOS do not have such an issue)

**Are you willing and able to create a PR request to fix this issue?**
No

**Logs**
Logs tell me, that both of the keycodes triggered `Control + c` activation (spelling is the same for both ru and en, but I didn't try to check ascii codes between them)

**Comment by greena13** [comment] 2019-06-03 07:04
Hi @Viperwow, thanks for bringing this to my attention. Truth be told, I have been concerned about i18n issues since I took over `react-hotkeys` - I've just been waiting for them to surface.

Let me see if I understand this correctly: you are defining your key combination with the (english) string `ctrl + c` and this works on an English keyboard, but not on a Russian keyboard. Is that correct?

**Comment by Viperwow** [comment] 2019-06-03 17:48
Yes, you're right. Only English keyboard layout works, but not the Russian one with the same keys.

**Comment by greena13** [comment] 2019-06-04 07:09
Thanks for confirming.

I'll have to think on this one further. The fact that you are using `HotKeys` (as opposed to `GlobalHotkeys`) means that the `key` attribute is coming through React's own key event handling. It does some minimal standardisation between browsers, but nothing to do with non-English keyboards, that I am aware of.

I don't trust my memory at this point, as it's been a long time since I looked into it, but I believe there may be issues with using the `keyCode` for users who are using alternative keyboard (non-Qwerty) layouts. (The `keyCode` of the physical is recorded, rather than the intended key.) So there may be a trade off to be considered here. I'll have to try and re-test this to be sure I'm not mis-remembering.

Perhaps we could solve your problem without creating any new ones with some sort of casting of `key` to the ASCII character set - not sure what the full implications or edge cases of doing so may be, though.

**Comment by greena13** [comment] 2019-06-17 17:12
Ok, I have done some further research and it seems like these are by all accounts different keys:

```
// English
'c'.charCodeAt(0)
99

// Russian
'с'.charCodeAt(0)
1089

'c' === 'с'
false
```

I can't say for sure whether the two keys will have the same `keyCode` value or not (I don't have access to a Russian keyboard) - but React will always use `key` over `keyCode`, if it's present. I am not willing, nor do I think it's a good idea, to start overriding the way React works - `react-hotkeys` is designed to be as unobtrusive and consistent with React as possible.

I also went down the route of looking into casting non-ASCII chars to their closes ASCII equivalent. There is no well-defined or reliable way of doing this, that won't undoubtably introduce more issues, so I'm afraid it's a no-go.

However, as of [v2.0.0-pre8](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre8) I do believe there is a work-around that will allow you to specify your own overrides:

```javascript
import {configure} from 'react-hotkeys';

configure({
  customKeyCodes: {
    1089: 'c'    
  }
})
```

This is effectively mapping the key code for the Russian с, to the ASCII 'c'. This will take precedence of what React does, and *should* work as intended (allowing you to define your key combinations in terms of the English 'c' and have it also work on Russian keyboards).

I am closing this issue for now, but please do let me know if the above workaround works for you, or if you have any further suggestions.

**Closed by greena13** 2019-06-17 17:12 UTC

**Comment by Viperwow** [comment] 2019-06-17 17:29
Thank you for your work! And, yes, I've come to the same workaround during my research, but with adding extra "Ctrl + c" (russian version) of the same key combination.

**Comment by greena13** [comment] 2019-06-17 21:56
No problem. I'm glad you were able to find a work around.
