### ISSUE TITLE
[BUG]  Cmd + Shift + 'c' calls the 'c' GlobalHotKey handler

### ISSUE THREAD

**Issue by snosenzo** [greena13/react-hotkeys#175] opened 2019-05-15 15:20 UTC
**Describe the bug**
The key sequence to active element selection in chrome (Cmd + Shift + 'c') is activating our 'c' hotkey handler. 
**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
Using GlobalHotkeys
**Expected behavior**
Pressing Cmd + Shift + c should not activate the 'c' function in GlobalHotkeys because modifier keys are being pressed, and should instead just enable Chrome element selection.

**Platform (please complete the following information):**
 - Version: 2.0.0-pre4
 - Browser: Chrome
 - OS: OSX

**Are you willing and able to create a PR request to fix this issue?**
maybe?

correct me if this is the expected behavior and there's something that I can do to override/customize this.

**Comment by greena13** [comment] 2019-05-16 06:56
Hi @snosenzo, thanks for filing your issue.

Unfortunately, this is indeed not surprising (and matches the intended behaviour of the package). If your problem was reversed, and you wanted the hotkey handler to override the browser handler, then I would direct you to the [Preventing default browser behaviour](https://github.com/greena13/react-hotkeys#preventing-default-browser-behaviour) section of the Readme.

However, your situation is a little messier and you will have to step outside or `react-hotkeys` for now ( a feature could be added in the future to declaratively do this). I suggest in your handler, you use the [KeyboardEvent's meta property](https://www.w3schools.com/jsref/event_key_metakey.asp) to abort executing whatever your handler does.

I'm closing this for now to help clarify the priority of outstanding issues that need to be addressed, but please let me know if you want to make a feature request to have this added to the library in perhaps a more scalable fashion (the approach above would need to be implemented for each individual handler function).

**Closed by greena13** 2019-05-16 06:56 UTC

**Comment by greena13** [comment] 2019-05-18 16:33
It may interest the reader to know that there is a ongoing similar discussion about when the longer key sequence is another application action, rather than a browser one: #161.

**Comment by greena13** [comment] 2019-06-02 19:45
@snosenzo, the fix should be available in [v2.0.0-pre7](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre7), so when you press `cmd+shift+c`, it won't trigger the `c` action.
