### ISSUE TITLE
[QUESTION] About matching key sequences

### ISSUE THREAD

**Issue by NepeinAV** [greena13/react-hotkeys#181] opened 2019-05-19 21:47 UTC
Hello Aleck! I have a question about how react-hotkeys matching key sequences like 'ctrl+alt+p'. 
In my project i have the structure of **<HotKeys />** components like:

`<HotKeys globalKeys>
...
<HotKeys editorKeys>
...
</HotKeys>`

In **globalKeys** i have, for example, key sequence 'CTRL+ALT+ARROWDOWN'. 
Also in **editorKeys** i have just 'ARROWDOWN' sequence. 
Now focus on **editorKeys**.

### Question
Why where I press **'CTRL+ALT+ARROWDOWN'** sequence react-hotkeys finds sub-match of it

> HotKeys (F3📙-E253💚-C0🔺-P1⭐️:) Found action that matches 'Alt+ArrowDown+Control' (sub-match: 'ArrowDown'): DOWN. Calling handler . . .

 and executing the **'ARROWDOWN'** handler instead of **'CTRL+ALT+ARROWDOWN'** handler and how to prevent sub-matching?

Thank you!

**Comment by greena13** [comment] 2019-05-30 18:26
Hello @NepeinAV, thanks for taking the time to clarify what the expected behaviour is and apologies for the delay in responding.

It seems you are among a growing number of users requesting that the library work in a different way than it currently does: That the length of the key combination be given priority over where its definition is in the focus tree. Currently `HotKey` and `GlobalHotKey` components that are closest to the component that is currently in focus, will have their keymaps and handlers inspected first, and if a match is found, then `react-hotkeys` looks no further. I am guessing this is why the shorter `ArrowDown` submatch is occurring in your case.

I am planning on obliging this growing sentiment, but it will be a while before I attempt to tackle it.

I'm going to close this issue for now, as for the purpose of addressing it, it appears to be a duplicate of #161. But feel free to ask further questions if anything remains unclear.

**Closed by greena13** 2019-05-30 18:26 UTC

**Comment by greena13** [comment] 2019-06-02 19:43
@NepeinAV, as of [v2.0.0-pre7](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre7) sub-matches are ignored, so `react-hotkeys` should behave as you're expecting.
